Thinking1高德地图中的路径规划原理是怎样的？

A：

理论上来说路径规划问题都是最短路径问题，那么最基础的算法就是Dijkstra，不过在查找相关资料中发现，还有很多提高路径规划算法效率的方法

参考：https://www.zhihu.com/question/24870090/answer/73834896


Thinking2 football.gml数据集中，美国大学生足球联赛，包括115支球队，被分为12个联盟。为什么使用LPA标签传播进行社区发现，只发现了11个社区？

A：

根据LPA算法得出的社区数与联盟数并不存在等价的关系。LPA是通过616场比赛得关系进行划分，社区数只与这些比赛有关而与地域无关


Thinking3微博采用了类似FaceBook的EdgeRank算法，如果你给微博的信息流做设计，你会如何设计？

A：

信息流设计

1、亲密度：博主回复评论、赞评论等来判断粉丝亲密度

2、内容质量：粉丝转发、评论微博、赞微博，在微博正文停留的时间来判断文章的内容质量

3、原创度：是否是转发，是否有相似博文

4、新鲜度：是否具有时效性等


In [3]:
#使用Python模拟下面的PageRank计算过程，求每个节点的影响力（迭代100次）
import numpy as np

a = np.array([[0, 0, 0, 1/3, 0, 0], 
            [1/4, 0, 0, 0, 1/2, 0],
            [0, 1, 0, 1/3, 1/2, 0],
            [1/4, 0, 0, 0, 0, 1],
            [1/4, 0, 1, 1/3, 0, 0],
            [1/4, 0, 0, 0, 0, 0]])

b = np.array([1/6, 1/6, 1/6, 1/6, 1/6, 1/6])
w = b

def work(a, w):
    for i in range(100):
        w = np.dot(a, w)
        print(w)

def random_work(a, w, n):
    d = 0.85
    for i in range(100):
        w = (1-d)/n + d*np.dot(a, w)
        print(w)
work(a, w)  
print('*******************************************************************************************')
random_work(a, w, 6)

[0.05555556 0.125      0.30555556 0.20833333 0.26388889 0.04166667]
[0.06944444 0.14583333 0.32638889 0.05555556 0.38888889 0.01388889]
[0.01851852 0.21180556 0.3587963  0.03125    0.36226852 0.01736111]
[0.01041667 0.18576389 0.40335648 0.02199074 0.37384259 0.00462963]
[0.00733025 0.18952546 0.38001543 0.0072338  0.4132909  0.00260417]
[0.00241127 0.20847801 0.39858218 0.00443673 0.38425926 0.00183256]
[0.00147891 0.19273245 0.40208655 0.00243538 0.4006639  0.00060282]
[8.11792695e-04 2.00701678e-01 3.93876190e-01 9.72543724e-04
 4.03268068e-01 3.69727366e-04]
[3.24181241e-04 2.01836982e-01 4.02659894e-01 5.72675540e-04
 3.94403319e-01 2.02948174e-04]
[1.90891847e-04 1.97282705e-01 3.99229534e-01 2.83993484e-04
 4.02931831e-01 8.10453104e-05]
[9.46644947e-05 2.01513638e-01 3.98843285e-01 1.28768272e-04
 3.99371921e-01 4.77229617e-05]
[4.29227573e-05 1.99709627e-01 4.01242522e-01 7.13890854e-05
 3.98909874e-01 2.36661237e-05]
[2.37963618e-05 1.99465667e-01 3.99188360e-01 3.43968130e-0

In [8]:
from textrank4zh import TextRank4Keyword, TextRank4Sentence


text = '''土耳其未炮击美军 土耳其向美军开战
当地时间11日，一支美国特种部队遭到了土耳其的炮弹袭击，《新闻周刊》称这明显是“误伤”。五角大楼一名高级官员说，土耳其军队的炮击非常猛烈，美国人员曾考虑进行还击是出于自卫。
《新闻周刊》10月11日报道，一名库尔德情报官员和五角大楼官员均表示，在库尔德人占多数的城市科巴尼的山上，这支特种部队在执行任务时遭到炮击，炮弹落在离驻扎地几百米远的地方，没有美国士兵受伤。
报道称，特种部队没有还击，而是在炮击停止后撤退。《新闻周刊》此前曾在周三报道说，目前美国军队的交战规则仍然以自卫为中心，五角大楼还没有发布全面撤出叙利亚的命令。
这名五角大楼官员说，土耳其部队应该了解美国的位置，不过，这名官员没有具体说明在场人员的确切人数，但表示大约在15到100人之间。《新闻周刊》已联系五角大楼就此事发表评论。
土耳其国防部针对《新闻周刊》的报道发表了一份声明，否认土耳其军队针对美国军队。土耳其国防部证实说，“土耳其在苏鲁奇以南的边境哨所，受到了来自美国一个观察哨西南方向大约1千米处山丘的迫击炮攻击。”
为了自卫，双方对袭击的恐怖分子阵地进行了还击。土耳其没有以任何方式向美国观察哨开火。他说：所有的预防措施都是在开火之前采取的，目的是防止对美军基地造成任何伤害。作为预防措施，我们在收到来自美国的信息后立即停火。我们坚决反对美国或联军部队遭到袭击的说法。
特朗普周四曾在社交媒体上表示，他有“三种选择之一：派遣数千名士兵并在军事上取胜，在经济上对土耳其进行严厉打击并实施制裁，或者在土耳其和库尔德人之间斡旋达成协议”
土耳其总统埃尔多安早就警告说，他将猛攻边境，建立一个所谓的“安全区”。白宫周日宣布，美国军队将在一旁待命。'''

# 输出关键词，设置文本小写，窗口为2
tr4w = TextRank4Keyword()
tr4w.analyze(text=text, lower=True, window=2)
print('关键词：')
for item in tr4w.get_keywords(20, word_min_len=1):
    print(item.word, item.weight)

# 输出重要的句子
tr4s = TextRank4Sentence()
tr4s.analyze(text=text, lower=True, source = 'all_filters')
print('摘要：')
# 重要性较高的三个句子
for item in tr4s.get_key_sentences(num=3):
	# index是语句在文本中位置，weight表示权重
    print(item.index, item.weight, item.sentence)

Building prefix dict from the default dictionary ...
Dumping model to file cache C:\Users\yczwx\AppData\Local\Temp\jieba.cache
Loading model cost 0.784 seconds.
Prefix dict has been built succesfully.


关键词：
土耳其 0.04069520917096793
美国 0.0369142527418084
说 0.02446922676052611
没有 0.023786570392058257
袭击 0.017700149279091273
特种部队 0.017412575896103233
炮击 0.017115219350455936
遭到 0.016625479650103248
报道 0.01588545076733542
进行 0.015360109277853728
官员 0.01289429340340466
新闻周刊 0.0124159192792039
军队 0.012101622809814312
炮弹 0.011975939251251714
还击 0.011652728049471862
观察哨 0.011553223050069785
边境 0.01152755141124453
城市 0.01117250958722105
科巴 0.01117250958722105
山丘 0.01117250958722105
摘要：
2 0.08591468923918809 五角大楼一名高级官员说，土耳其军队的炮击非常猛烈，美国人员曾考虑进行还击是出于自卫
5 0.0783434449568913 《新闻周刊》此前曾在周三报道说，目前美国军队的交战规则仍然以自卫为中心，五角大楼还没有发布全面撤出叙利亚的命令
6 0.07572455879841139 这名五角大楼官员说，土耳其部队应该了解美国的位置，不过，这名官员没有具体说明在场人员的确切人数，但表示大约在15到100人之间


In [11]:
import jieba
import jieba.analyse
import jieba.posseg as pseg

sentence = '''土耳其未炮击美军 土耳其向美军开战
当地时间11日，一支美国特种部队遭到了土耳其的炮弹袭击，《新闻周刊》称这明显是“误伤”。五角大楼一名高级官员说，土耳其军队的炮击非常猛烈，美国人员曾考虑进行还击是出于自卫。
《新闻周刊》10月11日报道，一名库尔德情报官员和五角大楼官员均表示，在库尔德人占多数的城市科巴尼的山上，这支特种部队在执行任务时遭到炮击，炮弹落在离驻扎地几百米远的地方，没有美国士兵受伤。
报道称，特种部队没有还击，而是在炮击停止后撤退。《新闻周刊》此前曾在周三报道说，目前美国军队的交战规则仍然以自卫为中心，五角大楼还没有发布全面撤出叙利亚的命令。
这名五角大楼官员说，土耳其部队应该了解美国的位置，不过，这名官员没有具体说明在场人员的确切人数，但表示大约在15到100人之间。《新闻周刊》已联系五角大楼就此事发表评论。
土耳其国防部针对《新闻周刊》的报道发表了一份声明，否认土耳其军队针对美国军队。土耳其国防部证实说，“土耳其在苏鲁奇以南的边境哨所，受到了来自美国一个观察哨西南方向大约1千米处山丘的迫击炮攻击。”
为了自卫，双方对袭击的恐怖分子阵地进行了还击。土耳其没有以任何方式向美国观察哨开火。他说：所有的预防措施都是在开火之前采取的，目的是防止对美军基地造成任何伤害。作为预防措施，我们在收到来自美国的信息后立即停火。我们坚决反对美国或联军部队遭到袭击的说法。
特朗普周四曾在社交媒体上表示，他有“三种选择之一：派遣数千名士兵并在军事上取胜，在经济上对土耳其进行严厉打击并实施制裁，或者在土耳其和库尔德人之间斡旋达成协议”
土耳其总统埃尔多安早就警告说，他将猛攻边境，建立一个所谓的“安全区”。白宫周日宣布，美国军队将在一旁待命。'''

# 获取分词
seg_list = jieba.cut(sentence, cut_all=False)
print(' '.join(seg_list))

'''# 获取分词和词性
words = pseg.cut(sentence)
for word, flag in words:
	print('%s, %s' % (word, flag))'''



# 通过TF-IDF获取关键词
keywords = jieba.analyse.extract_tags(sentence, topK=20, withWeight=True, allowPOS=('n','nr','ns'))
for item in keywords:
    print(item[0],item[1])
print('-'*100)

# 基于TextRank算法的关键词抽取
keywords = jieba.analyse.textrank(sentence, topK=20, withWeight=True, allowPOS=('n', 'ns')) 

print(keywords)
for item in keywords:
    print(item[0],item[1])

土耳其 未 炮击 美军   土耳其 向 美军 开战 
 当地 时间 11 日 ， 一支 美国 特种部队 遭到 了 土耳其 的 炮弹 袭击 ， 《 新闻周刊 》 称 这 明显 是 “ 误伤 ” 。 五角大楼 一名 高级官员 说 ， 土耳其 军队 的 炮击 非常 猛烈 ， 美国 人员 曾 考虑 进行 还击 是 出于 自卫 。 
 《 新闻周刊 》 10 月 11 日 报道 ， 一名 库尔德 情报 官员 和 五角大楼 官员 均 表示 ， 在 库尔德人 占多数 的 城市 科巴 尼 的 山上 ， 这支 特种部队 在 执行 任务 时 遭到 炮击 ， 炮弹 落 在 离 驻扎地 几百米 远 的 地方 ， 没有 美国士兵 受伤 。 
 报道 称 ， 特种部队 没有 还击 ， 而是 在 炮击 停止 后 撤退 。 《 新闻周刊 》 此前 曾 在 周三 报道 说 ， 目前 美国 军队 的 交战 规则 仍然 以 自卫 为 中心 ， 五角大楼 还 没有 发布 全面 撤出 叙利亚 的 命令 。 
 这名 五角大楼 官员 说 ， 土耳其 部队 应该 了解 美国 的 位置 ， 不过 ， 这名 官员 没有 具体 说明 在场 人员 的 确切 人数 ， 但 表示 大约 在 15 到 100 人 之间 。 《 新闻周刊 》 已 联系 五角大楼 就 此事 发表 评论 。 
 土耳其 国防部 针对 《 新闻周刊 》 的 报道 发表 了 一份 声明 ， 否认 土耳其 军队 针对 美国 军队 。 土耳其 国防部 证实 说 ， “ 土耳其 在 苏鲁 奇 以南 的 边境 哨所 ， 受到 了 来自 美国 一个 观察哨 西南 方向 大约 1 千米 处 山丘 的 迫击炮 攻击 。 ” 
 为了 自卫 ， 双方 对 袭击 的 恐怖分子 阵地 进行 了 还击 。 土耳其 没有 以 任何 方式 向 美国 观察哨 开火 。 他 说 ： 所有 的 预防措施 都 是 在 开火 之前 采取 的 ， 目的 是 防止 对 美军基地 造成 任何 伤害 。 作为 预防措施 ， 我们 在 收到 来自 美国 的 信息 后 立即 停火 。 我们 坚决 反对 美国 或 联军部队 遭到 袭击 的 说法 。 
 特朗普 周四 曾 在 社交 媒体 上 表示 ， 他 有 “ 三种 选择 之一 ： 派遣 数千名 士兵 并 在 军事 上 取胜 ， 在经济上 对 土耳